Feature/development
RokoVarano/TNW_clone2 pull request #1
Opened 2020-12-02 23:47 UTC by RokoVarano

Proyect is still in development. We needed to start from scratch today due to poor planning of code develoment. Right now, mobile site is not finished and Desktop site development has not started. Also readme has not been done yet.

Development will continue as fast as possible.

2020-12-03 00:44 UTC, descholar-ceo requested changes
# Status: Invalid Code Review Request :disappointed: :cry: :x: 
## :handshake: :handshake: :handshake:  Hello @RokoVarano and @widzthedvloper :hand: 
:x: Your code review request has been marked as invalid because your repository doesn't look professional, please [read this lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to know how you should make it professional.
### Some tips :traffic_light: 
:worried: You should add a custom readme file which follow microverse template
:worried: Make your pull request name meaningful, currently its name is Feature/development, that name is not meaningful at all. Make it descriptive; something like `add-nextweb-clone`... try things like that

2020-12-04 08:46 UTC, widzthedvloper commented
we fixed all the linter error related to the CSS and HTML file. 
we had use sass in are program the only linter error that remain are inside the sass file we used.
Since we didn't have to study sass completely for this week we have issues fixing them (sass wasn't mandatory for this project we use it for the last exercise of the week which an introduction to processors )

2020-12-04 09:38 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**
- [x] Please update your PR message. You are using the same message you used for the last review which got invalidated. 

<img width="676" alt="1" src="https://user-images.githubusercontent.com/58504655/101143272-78f01300-3638-11eb-96c0-df3df4181ef1.PNG">

- [x] In the future please make your commit messages descriptive. 

- [ ] Please remove linter errors. 
<img width="647" alt="2" src="https://user-images.githubusercontent.com/58504655/101143461-bce31800-3638-11eb-968f-20a2d4ddaa49.PNG">

- [x] Please use semantic HTML 
- only one <main> per page ;
- top-level element (in most cases) ;
- don't put your site's header/menu/footer (repeated content) in your <main>. can hold article header/footer if specific.

**Purpose**

The primary purpose of <main> is to map ARIA’s landmark role main** to an element in HTML. This will help screen readers and other assistive technologies understand where the main content begins. The W3C spec describes as representing:

Specs say

> The main content area consists of content that is directly related to or expands upon the central topic of a document or central functionality of an application.

### **Header/footer**
**Exclude site's header/footer/menu:**

excludes content that is repeated across a set of documents such as site navigation links, copyright information, site logos, and banners and search forms (unless the document or application's main function is that of a search form).

Continue to use `role='main'`
But as a side note to this article Steve Faulkner writes:

> You should still use the ARIA role until all browsers map the role to the <main> element.

- [x] Please use dry CSS. You have used many properties again and again. For example **display:flex**. You can learn more about dry CSS from [here](https://teamtreehouse.com/library/dry-css#:~:text=DRY%20stands%20for%20%22Don't,code%20in%20our%20style%20sheet.). 

# Desktop

### Navigation Bar

> Everything is fine here. Good work!

### Top 3 articles section

- [x] Plese change the from `background-color: antiquewhite` to` background-color:white`

**Clone**
<img width="950" alt="3" src="https://user-images.githubusercontent.com/58504655/101145618-dd60a180-363b-11eb-8c25-1974d65805a1.PNG">

**Code**
<img width="286" alt="3 1" src="https://user-images.githubusercontent.com/58504655/101145716-fcf7ca00-363b-11eb-950e-f9a1cd318fa8.PNG">

**Categories (Apps, Gear, Tech, etc) section**

- [x] Items should have a gap from each other. 

**Clone**
<img width="772" alt="4" src="https://user-images.githubusercontent.com/58504655/101146036-59f38000-363c-11eb-8b5c-482b65157c21.PNG">

**Original**

<img width="804" alt="4 1" src="https://user-images.githubusercontent.com/58504655/101146153-7b546c00-363c-11eb-81a8-de31e9907bce.PNG">

**Footer**

- [x] Footer has too much vertical width(height). Please work on it. 

<img width="949" alt="5" src="https://user-images.githubusercontent.com/58504655/101146319-ab9c0a80-363c-11eb-9ba1-d486e51a759b.PNG">

-------------------------------------------------------------

# Medium

- [x] Your whole webpage missing medium styling. You are mistakenly are given small version styling to the medium screen too.  Here are  some suggestions:

- On the navbar TWN logo appears at the leftmost part
- after the navbar in 3 article section TWN logo disappears
- Latest News section aligns 3 articles per row
- Latest funding section aligns 3 articles per row
- Categories (Apps, Gear, Tech, etc) section aligns 2 category boxes per row
- Latest deal section aligns 3 articles per row

---------------------------------------------------------------------

# Small

**Categories (Apps, Gear, Tech, etc) section** 

- [x] This should look like this 
<img width="576" alt="7" src="https://user-images.githubusercontent.com/58504655/101147259-f4a08e80-363d-11eb-9704-82305f346f2c.PNG"> 
But yours look like this

<img width="573" alt="6" src="https://user-images.githubusercontent.com/58504655/101147332-0c781280-363e-11eb-8849-558bf52fde5e.PNG">




**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-12-04 09:38 UTC, arslanbisharat commented on README.md
> +this website can be viewd better on the screen size of of 1920 X 1080 in Mozilla firefox browser.
- [x] Please use Grammarly to not get errors.

2020-12-04 09:38 UTC, arslanbisharat commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/rodrigo-ibaceta-a8657611a/)
- [x] Add authors name please

2020-12-04 09:38 UTC, arslanbisharat commented on README.md
> +Give a * if you like the project
- [ ] [Optional] You can add ⭐  by writing `:start: `in readme

2020-12-04 09:38 UTC, arslanbisharat commented on README.md
> +This project as no license
- [ ] Please remove this part or add a license

2020-12-04 09:38 UTC, arslanbisharat commented on index.html
> +</div>
- [ ] Please enclose this part in the header tags

2020-12-04 09:38 UTC, arslanbisharat commented on index.html
> +    </footer>
- [ ] Please move footer outside main

2020-12-04 19:50 UTC, abredi approved these changes
### Status: Approved 🙌 🎇
Hi @RokoVarano and @RokoVarano, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏👏  I appreciate your hard work in replicating thenextweb.com.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-05 14:47 UTC, closed without merging

2020-12-11 20:47 UTC, abredi commented
Hi @RokoVarano and @widzthedvloper, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏 You did well on this project. I appreciate your efforts to achieve this milestone 🦍. 

But, this project is already approved,  and it will mark as complete soon, so you don't have to create another code review request to microverse.

Thanks for your patience.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-11 21:25 UTC, eypsrcnuygr commented
Dear @widzthedvloper. I am not sure what you've mixed and what makes you struggle, however, I can not approve a project that is already approved. So I mark your submission as invalid and I highly recommend you to reach out to student success and explain the urgency of your problem. I am sure that they'll have the right resources to help you. 

Happy coding :100: 
Eyüp Sercan UYGUR